const xmlContainer = document.querySelector('.xmlContainer');
const jsonContainer = document.querySelector('.jsonContainer');
const input = document.querySelector('#fileInput');
const xmlInnerContainer = document.querySelector('.xmlInnerContainer');
const jsonInnerContainer = document.querySelector('.jsonInnerContainer');
const uploadBtn = document.querySelector('.uploadBtn');
const convertoJson = document.querySelector('.convertBtn');
const rewriteBtn = document.querySelector('.rewriteBtn');
const appendBtn = document.querySelector('.appendBtn');
const textArea = document.querySelector('.inputBox');
const editBtn = document.querySelector('.editIcon');
const clearBtn = document.querySelector('.clearBtn');
const downloadBtn = document.querySelector('.downloadBtn');
const popNewTab = document.querySelector('.newtabJsonBtn');
let xml;